[[animations]]
name = "particle"
rotation_speed = 0 #how much the animation rotates every game tick
filepath = "particle_default.png"
origin = {x = 4, y = 4} #where the animation should be drawn relative to
frames = [ #this contains every frame of the animation, and how many milliseconds it is shown
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 250 },
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 250 }
]

[[animations]]
name = "player"
rotation_speed = 0
filepath = "player.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 0, y = 0, width = 16, height = 32}, milliseconds = 250 }
]

[[animations]]
name = "slime"
rotation_speed = 0
filepath = "slime.png"
origin = {x = 16, y = 16}
frames = [
   { subrect = {x = 0, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]

[[animations]]
name = "cave_floor"
rotation_speed = 0
filepath = "tilemap.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 0, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]

[[animations]]
name = "cave_wall"
rotation_speed = 0
filepath = "tilemap.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 32, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]


[[animations]]
name = "fireball"
rotation_speed = 10 
filepath = "particle_default.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 1000 }
]

[[animations]]
name = "blood_particle"
rotation_speed = 10 
filepath = "blood.png"
origin = {x = 2, y = 2}
frames = [
   { subrect = {x = 0, y = 0, width = 4, height = 4}, milliseconds = 100 }
]


[[animations]]
name = "coin"
rotation_speed = 10 
filepath = "coin.png"
origin = {x = 3, y = 3}
frames = [
   { subrect = {x = 0, y = 0, width = 6, height = 6}, milliseconds = 100 }
]
