[[animations]]
name = "particle"
rotation_speed = 0 #how much the animation rotates every game tick
filepath = "particle_default.png"
origin = {x = 4, y = 4} #where the animation should be drawn relative to
frames = [ #this contains every frame of the animation, and how many milliseconds it is shown
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 250 },
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 250 }
]

[[animations]]
name = "player"
rotation_speed = 0
filepath = "player.png"
origin = {x = 8, y = 8}
frames = [
   { subrect = {x = 0, y = 0, width = 16, height = 32}, milliseconds = 250 }
]

[[animations]]
name = "slime"
rotation_speed = 0
filepath = "slime.png"
origin = {x = 16, y = 16}
frames = [
   { subrect = {x = 0, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]

[[animations]]
name = "cave_floor"
rotation_speed = 0
filepath = "tilemap.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 0, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]

[[animations]]
name = "cave_wall"
rotation_speed = 0
filepath = "tilemap.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 32, y = 0, width = 32, height = 32}, milliseconds = 1000 }
]


[[animations]]
name = "fireball"
rotation_speed = 0 
filepath = "fireball.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 0, y = 0, width = 7, height = 7}, milliseconds = 1000 }
]

[[animations]]
name = "fireball_explosion"
rotation_speed = 0 
filepath = "fireball.png"
origin = {x = 0, y = 0}
loop = false
frames = [
   { subrect = {x = 0, y = 7, width = 7, height = 7}, milliseconds = 100 },
   { subrect = {x = 0, y = 14, width = 7, height = 7}, milliseconds = 100 },
   { subrect = {x = 0, y = 21, width = 7, height = 7}, milliseconds = 100 },
   { subrect = {x = 0, y = 28, width = 7, height = 7}, milliseconds = 100 },
   { subrect = {x = 0, y = 35, width = 7, height = 7}, milliseconds = 100 },
]

[[animations]]
name = "blood_particle"
rotation_speed = 10 
filepath = "particle_default.png"
origin = {x = 4, y = 4}
frames = [
   { subrect = {x = 0, y = 0, width = 8, height = 8}, milliseconds = 5000 }
]


[[animations]]
name = "coin"
rotation_speed = 10 
filepath = "coin.png"
origin = {x = 0, y = 0}
frames = [
   { subrect = {x = 2, y = 2, width = 1, height = 1}, milliseconds = 100 }
]
